version: '3.8'

services:
  # Backend rodando em modo de desenvolvimento
  furry_friends_backend:
    image: node:20-slim
    working_dir: /usr/src/app
    command: ["sh", "-c", "apt-get update && apt-get install -y openssl libssl-dev && npm install && npx prisma generate && npm run start:dev"]
    ports:
      - "3333:3000"
    volumes:
      - ./furry-friends-agenda-backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - .env

  # Frontend rodando com o servidor de desenvolvimento do Vite
  furry_friends_frontend:
    image: node:20-slim
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./furry-friends-agenda-app:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080"

  # O serviço de banco de dados permanece o mesmo
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  # Prisma Studio para desenvolvimento
  prisma-studio:
    image: node:20-slim
    working_dir: /app
    command: ["sh", "-c", "npm install && npx prisma studio --hostname 0.0.0.0 --port 5555"]
    ports:
      - "5555:5555"
    volumes:
      - ./furry-friends-agenda-backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
