# Dockerfile para Desenvolvimento do Backend

FROM node:20-slim

WORKDIR /usr/src/app

# Instalar dependências do sistema para o Prisma
RUN apt-get update -y && apt-get install -y openssl libssl-dev

# Copiar package.json e lock file
COPY package*.json ./

# Instalar TODAS as dependências, incluindo devDependencies
RUN npm install

# Gera o Prisma Client para que ele esteja disponível para a aplicação
RUN npx prisma generate

# Copiar o resto do código da aplicação
# O volume montado no docker-compose irá sobrepor isso, 
# mas é bom ter para consistência se a imagem for construída sozinha.
COPY . .

# O comando será fornecido pelo docker-compose.test.yml
# Apenas expomos a porta que o NestJS usará.
EXPOSE 3000
